Controllers/SettingController.cs
using Core.Flash;
using Hangfire;
using KCC_App.Data;
using KCC_App.Helpers;
using KCC_App.KCCModels;
using KCC_App.Models;
using KCC_App.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KCC_App.Controllers
{
    [Authentication]
    public class SettingController : ControllerBase
    {
        private readonly ILogger<SettingController> _logger;
        private KCCConfig cCConfig;
        private readonly IFlasher f;
        readonly ApplicationDbContext dbContext;
        private readonly IConfiguration _configuration;
        public SettingController(ILogger<SettingController> logger, IConfiguration configuration, ApplicationDbContext context, IFlasher f)
        {
            _logger = logger;
            this._configuration = configuration;
            this.dbContext = context;
            this.f = f;
            this.cCConfig = context.KCCConfig.AsNoTracking().Include(x=>x.EncryptKey).Include(x=>x.Mapping).FirstOrDefault();
        }
        [HttpGet]
        public IActionResult Manage()
        {
           
            dbContext.Entry(this.cCConfig).State = EntityState.Detached;
            return View(this.cCConfig);
        }

       
        [HttpPost]
        public IActionResult SaveConfig(KCCConfig data)
        {
            
            //dbContext.Remove()
            dbContext.Update(data);
            dbContext.SaveChanges();
            f.Flash(Types.Success, "Config updated");
            //Flash("Config update", FlashLevel.Success);
            //Flash.Instance.Success("Config", "Config saved");
            //FlashMessage.Warning("Your error message");
            //this.cCConfig = dbContext.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
            return RedirectToAction("Manage");
        }
    }
}

Views/Setting/Manage.cshtml
@model KCC_App.KCCModels.KCCConfig
@{
    ViewData["Title"] = "Manage Setting";
}
@Html.PartialAsync("_Flash")
<div class="text-left">
    <h1 class="display-4">KCC Configuration</h1>
    @using (Html.BeginForm("SaveConfig", "Setting", FormMethod.Post))
    {

<table cellpadding="0" cellspacing="0">
    <tr>
        <th colspan="2" align="center">Person Details</th>
    </tr>
    <tr class="hide">
        <td>Id: </td>
        <td>
            @Html.TextBoxFor(m => m.Id)
        </td>
    </tr>
    <tr>
        <th colspan="2" align="center">Person Details</th>
    </tr>
    <tr>
        <td>Financial Year: </td>
        <td>
            
            @Html.DropDownListFor(m => m.FinancialYear, ViewBag.years as SelectList, new { @class = "form-control" })

           
        </td>
    </tr>
    <tr>
        <td>Bank Code: </td>
        <td>
            @Html.TextBoxFor(m => m.BankCode)
        </td>
    </tr>
    <tr>
        <td>AuthKey: </td>
        <td>
            @Html.TextBoxFor(m => m.AuthKey)
        </td>
    </tr>
    <tr>
        <td>EndPoint: </td>
        <td>
            @Html.TextBoxFor(m => m.EndPoint)
        </td>
    </tr>
            <tr class="hide">
        <td>EncryptKeyId: </td>
        <td>
            @Html.TextBoxFor(m => m.EncryptKey.EncryptKeyId)
        </td>
    </tr>
    <tr>
        <td>IV Key: </td>
        <td>
            @Html.TextBoxFor(m => m.EncryptKey.IVkey)
        </td>
    </tr>
    <tr>
        <td>EndPoint: </td>
        <td>
            @Html.TextBoxFor(m => m.EncryptKey.Secretkey)
        </td>
    </tr>
</table>
            <table>
                <tr>
                    <th colspan="2" align="center">Key</th>
                    <th colspan="2" align="center">Mapping</th>
                </tr>
                @foreach (var property in Model.Mapping.GetType().GetProperties())
                {
                    var value = property.GetValue(Model.Mapping);
                    var displaycss = property.Name == "MappingId" ? "none" : "block";
                    <tr style="display:@displaycss">
                        <td>@property.Name</td>
                        <td>
                            <input type="text" name="Mapping.@property.Name" value="@value" />
                        </td>
                    </tr>

                }

            </table>

            <input type="submit" class="btn btn-primary" value="Save" />
    }
    </div>