Controllers/BatchController.cs
using Core.Flash;
using Core.Flash.Model;
using DocumentFormat.OpenXml.Wordprocessing;
using KCC_App.Data;
using KCC_App.Helpers;
using KCC_App.KCCModels;
using KCC_App.Models;
using KCC_App.Services;
using KCC_App.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Crypto.Tls;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using System.Globalization;
using static Org.BouncyCastle.Math.EC.ECCurve;
using NPOI.SS.Formula.Functions;
using KCC_App.Interfaces;
using Hangfire;
using DocumentFormat.OpenXml.InkML;
using MathNet.Numerics.Distributions;
using MathNet.Numerics.LinearAlgebra.Factorization;
using DocumentFormat.OpenXml.Spreadsheet;

namespace KCC_App.Controllers
{
    //[Route("Batch")]
    [Authentication]
    public class BatchController : ControllerBase
    {
        private readonly ILogger<SettingController> _logger;
        private IHostingEnvironment Environment;
        private object ddlYears;
        readonly KCCConfig cCConfig;
        private readonly IFlasher f;
        readonly ApplicationDbContext dbContext;
        private readonly IConfiguration _configuration;
        private readonly IServiceRepository serviceRepository;
        private readonly IBackgroundJobs backgroundJobs;


        public BatchController(ILogger<SettingController> logger,
            IHostingEnvironment _environment,
            IConfiguration configuration,
            ApplicationDbContext context,
            IFlasher f,
            IServiceRepository serviceRepository,
            IBackgroundJobs backgroundJobs)
        {
            _logger = logger;
            Environment = _environment;
            this._configuration = configuration;
            this.dbContext = context;
            cCConfig = dbContext.KCCConfig.FirstOrDefault();//  Common.GetKCCConfig(this._configuration);
            this.f = f;
            this.serviceRepository = serviceRepository;
            this.backgroundJobs = backgroundJobs;
            //this.cCConfig = context.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
        }
        public IActionResult List(int status, int? page = 1, string qry = "")
        {
            ViewData["CurrentFilter"] = qry;
            if (page != null && page < 1)
            {
                page = 1;
            }

            var pageSize = 10;
            var batches = this.dbContext.Batches.Include(x => x.BatchResponse).Include(x => x.BatchResponseData)
                .Include("BatchResponseData.BatchStatus");
            if (!string.IsNullOrEmpty(qry))
            {
                batches = batches.Where(x => x.batchId.ToLower().Contains(qry.ToLower()) || x.BatchResponseData.batchAckId.ToLower().Contains(qry.ToLower())
                    || x.financialYear.ToLower().Contains(qry.ToLower()) || x.BatchResponseData.BatchStatus.Name.ToLower().Contains(qry.ToLower()));

            }
            var finalData = batches.Where(ap => ap.BatchResponseData.status == status || status == 0)
                    .Where(x => x.financialYear == HttpContext.Session.GetString(Models.Constants.KEY_FINANCIALYEAR)).OrderByDescending(x => x.dateTime)
            .ToPagedList(page ?? 1, pageSize);
            return View(finalData);
        }
        public IActionResult Detail(string id)
        {

            var model = this.dbContext.Batches
                    .Include(x => x.BatchResponseData)
                    .Include(x => x.applications)

                    .Include("BatchResponseData.BatchStatus")
                    .Include("applications.basicDetails")
                    .Include("applications.accountDetails")
                    .Include("applications.loanDetails")
                    .Include("applications.AppStatus")
                    .FirstOrDefault(x => x.batchId == id);
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> RefreshBatches(int? page = 1)
        {
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            string jobId=  BackgroundJob.Enqueue<BackgroundJobs>(x => x.RefreshBatchStatus());
            return RedirectToAction("List", new { page = page });
        }

        [HttpGet]
        public async Task<IActionResult> RefreshBatchStatus(string batchAckId, string batchId)
        {
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            await backgroundJobs.RefreshBatchStatus(batchAckId, batchId);

            return RedirectToAction("Detail", new { id = batchId });
        }
        public IActionResult Applications(int status = 0, int? page = 1, string qry = "")
        {
          
            ViewData["CurrentFilter"] = qry;
            if (page != null && page < 1)
            {
                page = 1;
            }

            var pageSize = 10;

            var model = this.dbContext.Applications.Include(x => x.accountDetails).Include(x => x.basicDetails).Include(x => x.loanDetails)
                .Include(x => x.AppStatus).Where(ap => ap.AppStatus.status == status || status == 0);

            if (!string.IsNullOrEmpty(qry))
            {
                model = model.Where(ap => ap.uniqueId.ToLower().Contains(qry.ToLower()) || ap.accountDetails.accountNumber.ToLower().Contains(qry.ToLower()) ||
                ap.basicDetails.beneficiaryName.ToLower().Contains(qry.ToLower()) || ap.basicDetails.mobile.ToLower().Contains(qry.ToLower()));

            }
            var app = model.OrderByDescending(x => x.uniqueId).ToPagedList(page ?? 1, pageSize);
            return View(app);
        }
        public IActionResult Application(string id)
        {
            var model = this.dbContext.Applications

                .Include(x => x.accountDetails)
                .Include(x => x.basicDetails)
                .Include(x => x.residentialDetails)
                .Include(x => x.loanDetails)
                .Include(x => x.activities)
                .Include(x => x.AppStatus)
                .Include("activities.activityRows")
                .FirstOrDefault(x => x.uniqueId == id);
            return View(model);
        }
        public IActionResult DeleteMultiple(string batchId,List<string> rows)
        {
            foreach (var rowId in rows)
            {
                var row = dbContext.Applications.Find(rowId);
                if (row != null)
                {
                    row.isDeleted = 1;
                    dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Detail", new {id = batchId});
        }
        public IActionResult DeleteMultipleApplications(string batchId, List<string> rows)
        {
            foreach (var rowId in rows)
            {
                var row = dbContext.Applications.Find(rowId);
                if (row != null)
                {
                    row.isDeleted = 1;
                    dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Applications");
        }
        public async Task<IActionResult> DeleteApplicationBatch(string id,string batchId,string batchAckId)
        {
            var model = this.dbContext.Applications;
            var row = model.FirstOrDefault(m => m.uniqueId == id);
            ViewBag.data = id;

            //Call the api for deletion and if success then delete from local
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            try
            {
                await serviceRepository.DeleteApplication(new List<string>(new[]{id}), batchId, batchAckId);
                f.Success("Application Deleted successfully");
            }
            catch (Exception ex)
            {
                f.Danger(ex.Message);
            }
            ////dbContext.SaveChanges();
            return RedirectToAction("Detail",new {id=batchId});
        }
        public async Task<IActionResult> DeleteApplicationList(string id,string batchId,string batchAckId)
        {
            var model = this.dbContext.Applications;
            var row = model.FirstOrDefault(m => m.uniqueId == id);

            ViewBag.data = id;

            //Call the api for deletion and if success then delete from local
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            try
            {
                await serviceRepository.DeleteApplication(new List<string>(new[]{id}), batchId,batchAckId);
                f.Success("Application Deleted successfully");
            }
            catch (Exception ex)
            {
                f.Danger(ex.Message);
            }
            ////dbContext.SaveChanges();
            return RedirectToAction("Applications");
        }


        [HttpPost]
        public async Task<IActionResult> UploadBatch(IFormFile postedFile)
        {
            if (postedFile != null)
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string batchId = Common.BatchId(cCConfig.BankCode, dbContext);
                string fileName = batchId + ".xls";// Path.GetFileName(postedFile.FileName);

                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {

Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KCC_App.Models;
using KCC_App.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;

using System.IO;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using KCC_App.Utils;
using KCC_App.Services;
using KCC_App.KCCModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace KCC_App.Controllers
{
    [Authentication]
    public class TransactionController : ControllerBase
    {
        
        //private IHostingEnvironment Environment;
       
        //readonly KCCConfig cCConfig;
        
        //private readonly IConfiguration Configuration;
        //private readonly ApplicationDbContext _context;
        //public TransactionController(ApplicationDbContext context,IHostingEnvironment _environment, IConfiguration _configuration)
        //{
        //    _context = context;
        //    Environment = _environment;
        //    Configuration = _configuration;
        //    cCConfig = Common.GetKCCConfig(_configuration);
        //}
        //public IActionResult Index()
        //{
        //    return View();
        //}
       
        //[HttpGet]
        //public IActionResult Batch()
        //{
        //    var ap = _context.Batches.Include(x=>x.BatchResponse).ToList();
        //    return View(ap);
        //}
        //public IActionResult application(string id)
        //{
        //    var ap  = _context.Applications.Include(x => x.basicDetails).Include(x => x.loanDetails)
        //        .Include(x => x.accountDetails).Include(x=>x.Batch).Include(x=>x.Batch.BatchResponse).FirstOrDefault(x => x.batchId == id);
        //    return View(ap);

        //}
        //public IActionResult Details(string id)
        //{
        //    var dt = _context.Applications.Include(x=>x.basicDetails).Include(x=>x.loanDetails).Include(x => x.activities)
        //        .Include(x => x.Batch).FirstOrDefault(x=>x.batchId==id);
        //    return View(dt);

        //}
        //[HttpGet]
        //public IActionResult Applications()
        //{
        //    var ap = _context.Applications.ToList();
        //    return View(ap);
        //}

        //[HttpPost]
        //public async Task<IActionResult> UploadBatch(IFormFile postedFile)
        //{
           
        //    if (postedFile != null)
        //    {
        //        string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
        //        if (!Directory.Exists(path))
        //        {
        //            Directory.CreateDirectory(path);
        //        }
        //        string batchId = Common.BatchId(cCConfig.BankCode, _context);
        //        string fileName = batchId + ".xls";// Path.GetFileName(postedFile.FileName);
        //        string filePath = Path.Combine(path, fileName);
        //        using (FileStream stream = new FileStream(filePath, FileMode.Create))
        //        {
        //            postedFile.CopyTo(stream);
        //        }
        //        DataTable dataTable = Common.ExcelToDataTable(filePath, 0);
        //        BackgroundJobs backgroundJobs = new BackgroundJobs(Configuration,_context);
        //        BatchResponse ret = await backgroundJobs.FileUpload( new UploadModel
        //        {
        //            dt=dataTable,
        //            batchId=batchId,
        //            filePath=filePath

        //        });
        //        if (!string.IsNullOrEmpty(ret.error))
        //            SetFlash(Helpers.FlashMessageType.Error, ret.error);
        //        else
        //            SetFlash(Helpers.FlashMessageType.Success, String.Format("Batch uploaded successfully with AcknowledmentId {0}", ret.batchId));

        //        return RedirectToAction("Batch");
        //    }
        //    return null;
        //}
    }
   
}

    
                    

Views/Transaction/Batch.cshtml
@model List<KCC_App.KCCModels.Batch>

@{ ViewData["Title"] = "Home Page";
    Layout = "/views/shared/_layout.cshtml"; }


<head>

    <style>
        div.scroll {
            width: 1100px;
            height: 250px;
            overflow-x: hidden;
            overflow-y: auto;
            text-align: center;
        }

        * {
            box-sizing: border-box;
        }

        #myInput {
            background-image: url('/css/searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            width: 30%;
            font-size: 14px;
            /* padding: 12px 20px 12px 40px;*/
            border: 1px solid #ddd;
            margin-bottom: 12px;
            height: 40px;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th {
                text-align: left;
                padding: 12px;
                position: sticky;
                top: 0px;
            }

            #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: #f1f1f1;
                }




        .file-upload {
            background-color: #ffffff;
            width: 450px;
            margin: 0 auto;
            padding: 0px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

            .file-upload-btn:hover {
                background: #1AA059;
                color: #ffffff;
                transition: all .2s ease;
                cursor: pointer;
            }

            .file-upload-btn:active {
                border: 0;
                transition: all .2s ease;
            }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 0px;
            border: 1px dashed gray;
            position: relative;
            height: 100px;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

            .drag-text h3 {
                font-weight: 100;
                text-transform: uppercase;
                color: #15824B;
                padding: 60px 0;
            }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

            .remove-image:hover {
                background: #c13b2a;
                color: #ffffff;
                transition: all .2s ease;
                cursor: pointer;
            }

            .remove-image:active {
                border: 0;
                transition: all .2s ease;
            }
    </style>
</head>
<body>
    @*@Html.Partial("_Flash")*@
    <h2>Batch</h2>


    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group" role="group" aria-label="First group">
            <div style="width:240px;">
                <div style="float: left;">
                    <button class="btn btn-primary" style=" width: 100px;">
                        Excel
                    </button>
                </div>
                <div style="float: right;">
                    <button class="btn btn-primary" style=" width: 100px;">
                        Sync
                    </button>
                </div>
            </div>
        </div>

        <div class="input-group">
            <div class="input-group">
                <input type="search" class="form-control rounded" id="myInput" onkeyup="myFunction()" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                <div class="input-group-append" style=" margin-left: 5px;">
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalPush" style=" height: 40px;">Upload</button>
                </div>
            </div>
        </div>
    </div>

    <div class="scroll">
        <table id="myTable">
            <tr class="header">
                <th style="width:20%;">Serial NO.</th>
                <th style="width:10%;">Batch ID</th>
                <th style="width:20%;">Ackn No.</th>
                <th style="width:20%;">Financial Year</th>
                <th style="width:20%;">Submitted On</th>
                <th style="width:10%;">Status</th>
                <th style="width:10%;"></th>
            </tr>
            <tr>
                @foreach(var x in Model)
                {
                    var index = @Model.IndexOf(x) + 1;
                  <tr class="text-center">
                      <td>@index</td>
                        <td>@x.batchId</td>
                        <td>@x.BatchResponse.batchId</td>
                        <td>@x.financialYear</td>
                        <td>@x.dateTime</td>
                        <td>@x.BatchResponse.status</td>
                        <td>
                            
                            <a asp-controller="Transaction" asp-action="application" asp-route-id="@x.batchId" >
                            <input type="submit" class="btn btn-primary" value="View" /></a>
                        </td>
                    </tr>
                }
           
        </table>
    </div>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
    </div>
</body>


<div class="modal fade" id="modalPush" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-notify modal-info" role="document">
        <!--Content-->
        <div class="modal-content text-center">
            <!--Header-->
            <div class="modal-header d-flex justify-content-center">
                <p class="heading">Upload</p>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!--Body-->
            <div class="modal-body">
                <script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
                <div class="file-upload">

                    @*<button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>*@

                    <div class="image-upload-wrap">
                        @*<input type="file" class="form-control" id="customFile" onclick="$('.file-upload-input').trigger( 'click' )"  />*@
                        <input class="file-upload-input" type='file' name='file' id='file' onchange="loadFile(event)" accept=".xls/*" />
                        <div class="drag-text">
                            <i class=" fa fa-cloud-upload " aria-hidden="true" style="margin: 25px 0 0 2px; font-size: 55px; "></i>
                        </div>
                    </div>
                </div>



                <div class="modal-footer flex-center">
                    <a href="~/excel/kcc.xls" class="btn btn-primary">Sample</a>
                    <form asp-controller="Transaction" asp-action="UploadBatch" method="post" enctype="multipart/form-data">
                        <input type="file" name="postedFile" />
                        <input type="submit" value="Upload File" />
                    </form>
                    <a type="button" class="btn btn-outline-info waves-effect" data-dismiss="modal">Clear</a>
                </div>
            </div>

        </div>
    </div>
</div>

Views/Transaction/application.cshtml
@model KCC_App.KCCModels.Application

@{ ViewData["Title"] = "Home Page";
    Layout = "/views/shared/_layout.cshtml";

 }
<div>
    <h2>Batch Details</h2>
</div>

  <div class="row">
      <div class="col">
          <label for="formGroupExampleInput" class="form-label">BATCH ID</label>
          @Html.TextBoxFor(m => m.batchId)

      </div>
      <div class="col">
          <label for="formGroupExampleInput2" class="form-label">FINANCIAL YEAR</label>
          @Html.TextBoxFor(m => m.Batch.financialYear)

      </div>
      <div class="col">
          <label for="formGroupExampleInput2" class="form-label">BATCH STATUS</label>
          @Html.TextBoxFor(m => m.Batch.BatchResponse.status)


      </div>
</div>



<head>

    <style>
        div.scroll {
            width: 1100px;
            height: 250px;
            overflow-x: hidden;
            overflow-y: auto;
            text-align: center;
        }

        * {
            box-sizing: border-box;
        }

        #myInput {
            background-image: url('/css/searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            width: 30%;
            font-size: 14px;
            /* padding: 12px 20px 12px 40px;*/
            border: 1px solid #ddd;
            margin-bottom: 12px;
            height: 40px;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th {
                text-align: left;
                padding: 12px;
                position: sticky;
                top: 0px;
            }

            #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: #f1f1f1;
                }




        .file-upload {
            background-color: #ffffff;
            width: 450px;
            margin: 0 auto;
            padding: 0px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

            .file-upload-btn:hover {
                background: #1AA059;
                color: #ffffff;
                transition: all .2s ease;
                cursor: pointer;
            }

            .file-upload-btn:active {
                border: 0;
                transition: all .2s ease;
            }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 0px;
            border: 1px dashed gray;
            position: relative;
            height: 100px;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

            .drag-text h3 {
                font-weight: 100;
                text-transform: uppercase;
                color: #15824B;
                padding: 60px 0;
            }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

            .remove-image:hover {
                background: #c13b2a;
                color: #ffffff;
                transition: all .2s ease;
                cursor: pointer;
            }

            .remove-image:active {
                border: 0;
                transition: all .2s ease;
            }
    </style>
</head>
<body>
    <h2>Application</h2>
    <div class="scroll">
        <table id="myTable">
            <tr class="header">
                <th style="width:10%;">Ackn No.</th>
                <th style="width:20%;">Application ID</th>
                <th style="width:20%;">Account No.</th>
                <th style="width:20%;">Beneficiary Name</th>
                <th style="width:10%;">Mobile No.</th>
                <th style="width:10%;">Farmer Category</th>
                <th style="width:10%;">Record Status</th>
                <th></th>

            </tr>
            <tr>
                <td>@Model.batchId</td>
                <td>@Model.uniqueId</td>
                <td>@Model.accountDetails.accountNumber</td>
                <td>@Model.basicDetails.beneficiaryName</td>
                <td>@Model.basicDetails.mobile</td>
                <td>@Model.basicDetails.farmerCategory</td>
                <td>@Model.recordStatus</td>
                <td>
                    <a asp-controller="Transaction" asp-action="Details" asp-route-id="@Model.batchId">
                        <input type="submit" class="btn btn-primary" value="View" />
                    </a>
                </td>
            </tr>
            </table>
    </div>

        <script>
            function myFunction() {
               
                input = document.getElementById("myInput");
                
            }
        </script>
    </body>