Controllers/BatchController.cs
using Core.Flash;
using Core.Flash.Model;
using DocumentFormat.OpenXml.Wordprocessing;
using KCC_App.Data;
using KCC_App.Helpers;
using KCC_App.KCCModels;
using KCC_App.Models;
using KCC_App.Services;
using KCC_App.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Crypto.Tls;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using System.Globalization;
using static Org.BouncyCastle.Math.EC.ECCurve;
using NPOI.SS.Formula.Functions;
using KCC_App.Interfaces;
using Hangfire;
using DocumentFormat.OpenXml.InkML;
using MathNet.Numerics.Distributions;
using MathNet.Numerics.LinearAlgebra.Factorization;
using DocumentFormat.OpenXml.Spreadsheet;

namespace KCC_App.Controllers
{
    //[Route("Batch")]
    [Authentication]
    public class BatchController : ControllerBase
    {
        private readonly ILogger<SettingController> _logger;
        private IHostingEnvironment Environment;
        private object ddlYears;
        readonly KCCConfig cCConfig;
        private readonly IFlasher f;
        readonly ApplicationDbContext dbContext;
        private readonly IConfiguration _configuration;
        private readonly IServiceRepository serviceRepository;
        private readonly IBackgroundJobs backgroundJobs;


        public BatchController(ILogger<SettingController> logger,
            IHostingEnvironment _environment,
            IConfiguration configuration,
            ApplicationDbContext context,
            IFlasher f,
            IServiceRepository serviceRepository,
            IBackgroundJobs backgroundJobs)
        {
            _logger = logger;
            Environment = _environment;
            this._configuration = configuration;
            this.dbContext = context;
            cCConfig = dbContext.KCCConfig.FirstOrDefault();//  Common.GetKCCConfig(this._configuration);
            this.f = f;
            this.serviceRepository = serviceRepository;
            this.backgroundJobs = backgroundJobs;
            //this.cCConfig = context.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
        }
        public IActionResult List(int status, int? page = 1, string qry = "")
        {
            ViewData["CurrentFilter"] = qry;
            if (page != null && page < 1)
            {
                page = 1;
            }

            var pageSize = 10;
            var batches = this.dbContext.Batches.Include(x => x.BatchResponse).Include(x => x.BatchResponseData)
                .Include("BatchResponseData.BatchStatus");
            if (!string.IsNullOrEmpty(qry))
            {
                batches = batches.Where(x => x.batchId.ToLower().Contains(qry.ToLower()) || x.BatchResponseData.batchAckId.ToLower().Contains(qry.ToLower())
                    || x.financialYear.ToLower().Contains(qry.ToLower()) || x.BatchResponseData.BatchStatus.Name.ToLower().Contains(qry.ToLower()));

            }
            var finalData = batches.Where(ap => ap.BatchResponseData.status == status || status == 0)
                    .Where(x => x.financialYear == HttpContext.Session.GetString(Models.Constants.KEY_FINANCIALYEAR)).OrderByDescending(x => x.dateTime)
            .ToPagedList(page ?? 1, pageSize);
            return View(finalData);
        }
        public IActionResult Detail(string id)
        {

            var model = this.dbContext.Batches
                    .Include(x => x.BatchResponseData)
                    .Include(x => x.applications)

                    .Include("BatchResponseData.BatchStatus")
                    .Include("applications.basicDetails")
                    .Include("applications.accountDetails")
                    .Include("applications.loanDetails")
                    .Include("applications.AppStatus")
                    .FirstOrDefault(x => x.batchId == id);
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> RefreshBatches(int? page = 1)
        {
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            string jobId=  BackgroundJob.Enqueue<BackgroundJobs>(x => x.RefreshBatchStatus());
            return RedirectToAction("List", new { page = page });
        }

        [HttpGet]
        public async Task<IActionResult> RefreshBatchStatus(string batchAckId, string batchId)
        {
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            await backgroundJobs.RefreshBatchStatus(batchAckId, batchId);

            return RedirectToAction("Detail", new { id = batchId });
        }
        public IActionResult Applications(int status = 0, int? page = 1, string qry = "")
        {
          
            ViewData["CurrentFilter"] = qry;
            if (page != null && page < 1)
            {
                page = 1;
            }

            var pageSize = 10;

            var model = this.dbContext.Applications.Include(x => x.accountDetails).Include(x => x.basicDetails).Include(x => x.loanDetails)
                .Include(x => x.AppStatus).Where(ap => ap.AppStatus.status == status || status == 0);

            if (!string.IsNullOrEmpty(qry))
            {
                model = model.Where(ap => ap.uniqueId.ToLower().Contains(qry.ToLower()) || ap.accountDetails.accountNumber.ToLower().Contains(qry.ToLower()) ||
                ap.basicDetails.beneficiaryName.ToLower().Contains(qry.ToLower()) || ap.basicDetails.mobile.ToLower().Contains(qry.ToLower()));

            }
            var app = model.OrderByDescending(x => x.uniqueId).ToPagedList(page ?? 1, pageSize);
            return View(app);
        }
        public IActionResult Application(string id)
        {
            var model = this.dbContext.Applications

                .Include(x => x.accountDetails)
                .Include(x => x.basicDetails)
                .Include(x => x.residentialDetails)
                .Include(x => x.loanDetails)
                .Include(x => x.activities)
                .Include(x => x.AppStatus)
                .Include("activities.activityRows")
                .FirstOrDefault(x => x.uniqueId == id);
            return View(model);
        }
        public IActionResult DeleteMultiple(string batchId,List<string> rows)
        {
            foreach (var rowId in rows)
            {
                var row = dbContext.Applications.Find(rowId);
                if (row != null)
                {
                    row.isDeleted = 1;
                    dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Detail", new {id = batchId});
        }
        public IActionResult DeleteMultipleApplications(string batchId, List<string> rows)
        {
            foreach (var rowId in rows)
            {
                var row = dbContext.Applications.Find(rowId);
                if (row != null)
                {
                    row.isDeleted = 1;
                    dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Applications");
        }
        public async Task<IActionResult> DeleteApplicationBatch(string id,string batchId,string batchAckId)
        {
            var model = this.dbContext.Applications;
            var row = model.FirstOrDefault(m => m.uniqueId == id);
            ViewBag.data = id;

            //Call the api for deletion and if success then delete from local
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            try
            {
                await serviceRepository.DeleteApplication(new List<string>(new[]{id}), batchId, batchAckId);
                f.Success("Application Deleted successfully");
            }
            catch (Exception ex)
            {
                f.Danger(ex.Message);
            }
            ////dbContext.SaveChanges();
            return RedirectToAction("Detail",new {id=batchId});
        }
        public async Task<IActionResult> DeleteApplicationList(string id,string batchId,string batchAckId)
        {
            var model = this.dbContext.Applications;
            var row = model.FirstOrDefault(m => m.uniqueId == id);

            ViewBag.data = id;

            //Call the api for deletion and if success then delete from local
            //BackgroundJobs backgroundJobs = new BackgroundJobs(this._configuration, this.dbContext);
            try
            {
                await serviceRepository.DeleteApplication(new List<string>(new[]{id}), batchId,batchAckId);
                f.Success("Application Deleted successfully");
            }
            catch (Exception ex)
            {
                f.Danger(ex.Message);
            }
            ////dbContext.SaveChanges();
            return RedirectToAction("Applications");
        }


        [HttpPost]
        public async Task<IActionResult> UploadBatch(IFormFile postedFile)
        {
            if (postedFile != null)
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string batchId = Common.BatchId(cCConfig.BankCode, dbContext);
                string fileName = batchId + ".xls";// Path.GetFileName(postedFile.FileName);

                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {

Views/Batch/Applications.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@model IPagedList<KCC_App.KCCModels.Application>

@{ ViewData["Title"] = "Application List"; }


@Html.Partial("_Flash")


<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row hide">
            <div class="col-sm-12 text-right">
                <div class="card">
                    <div class="card-footer">
                        @*<button class="btn btn-sm btn-primary" type="submit" data-toggle="modal" data-target="#myModal">
                            <i class="fa fa-upload"></i> Upload
                            </button>
                            <button class="btn btn-sm btn-primary" type="reset">
                                <i class="fa fa-refresh"></i> Refresh
                            </button>*@
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-7"><strong><h4>Application List</h4></strong></div>
                            <div class="col-md-5" style="float: right;">
                                <div class="row">

                                    <div class="col-md-12" align="right">
                                        <div class="btn-group">
                                            <form action="/Batch/List" method="post">
                                                <div class="form-actions no-color">
                                                    <div class="btn-group mr-2" role="group" aria-label="First group">
                                                        <input type="text" hidden name="page" value="@Model.PageNumber" />
                                                        <input type="text" class="search form-control form-control-sm" margin-left name="qry" value="@ViewData["CurrentFilter"]" />
                                                        <input type="submit" value="Search" class="btn btn-sm btn-primary" />
                                                    </div>

                                                </div>
                                            </form>
                                        </div>
                                        <div class="btn-group mr-2" role="group" aria-label="First group">
                                            <button class="btn btn-sm btn-primary" type="reset" onClick="document.location.reload(true)">
                                                <i class="fa fa-refresh"></i> Refresh
                                            </button>
                                        </div>
                                        <div class="btn-group mr-2" role="group" aria-label="First group">
                                            @if (!string.IsNullOrEmpty(Model.First().applicationNumber))
                                            {
                                                <button id="delete" class="btn btn-sm btn-danger" style="display: none;" onclick="location.href='@Url.Action("DeleteMultipleApplications", "Batch",new {batchId = Model.First().batchId})'">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table  id="myTable" class="table table-responsive-sm table-bordered table-striped table-sm">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Batch No</th>
                                    <th>Unique Id</th>
                                    <th>Application No.</th>
                                    <th>Farmer Id</th>
                                    <th>Account No.</th>
                                    <th>Beneficiary Name</th>
                                    <th>Mobile No.</th>
                                    
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var x in Model)
                                {
                                    <tr data-row-id="@x.applicationNumber">
                                        <td><input type="checkbox" data-checkbox-id="@x.applicationNumber"></td>
                                        <td>@x.batchId</td>
                                        <td>@x.uniqueId</td>
                                        <td>@x.applicationNumber</td>
                                        <td>@x.farmerId</td>
                                        <td>@x.accountDetails.accountNumber</td>
                                        <td>@x.basicDetails.beneficiaryName</td>
                                        <td>@x.basicDetails.mobile</td>
                                       
                                        <td>@x.loanDetails.kccLimitSanctionedAmount</td>
                                        @if (@x.errors != null && @x.errors.Count() > 0)
                                        {
                                            <td>Failure</td>
                                        }
                                        else
                                        {
                                            <td>@x.AppStatus.Name</td>
                                        }
                                        <td>
                                            <a asp-controller="Batch" asp-action="Application" asp-route-id="@x.uniqueId">
                                                <button class="btn btn-sm btn-primary" type="submit">
                                                    <i class="fa fa-eye"></i> 
                                                </button>
                                            </a>
                                            @if (!string.IsNullOrEmpty(x.applicationNumber))
                                            {
                                                <a href="@Url.Action("DeleteApplicationList", "Batch",new {id=x.applicationNumber,batchId=x.batchId})">
                                                    <button class="btn btn-sm btn-danger" type="submit">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <nav>
                            @Html.PagedListPager(Model, page => Url.Action("Applications", new { page = page }), new PagedListRenderOptions()
                            {
                            ActiveLiElementClass = "active",
                            PageClasses = new[]{ "page-link"},
                            LiElementClasses=new[] { "page-item" },
                            UlElementClasses = new[] { "pagination","mt-3" },
                            LinkToNextPageFormat = "Next",
                            LinkToPreviousPageFormat = "Previous",
                            MaximumPageNumbersToDisplay = 10,
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                            DisplayLinkToNextPage = PagedListDisplayMode.Always
                            })
                          
                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center ">
                <div>
                    <h4 class="modal-title ">Upload</h4>
                </div>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div>
                    <form action="/action_page.php">
                        <input type="file" id="myFile" name="filename">
                    
                    </form>
                </div>
            </div>
            <div class="modal-footer" >
                
                        <button class="btn btn-primary" type="button"><i class="fa fa-download"></i> Download Sample</button>
                        <button class="btn btn-primary" type="button"><i class="fa fa-upload"></i> Upload</button>
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
              </div>
                
        </div>
       
    </div>
    
</div>
<script>
    $(document).ready(function () {
        $('#myTable input[type="checkbox"]').on('change', function () {
            var anyCheckboxSelected = $('#myTable input[type="checkbox"]:checked').length > 0;
            $('#delete').toggle(anyCheckboxSelected); // Show or hide delete button based on checkbox selection
        });

        $('#delete').on('click', function () {
            var selectedRows = [];
            $('#myTable input:checked').each(function () {
                var rowId = $(this).data('checkbox-id');
                selectedRows.push(rowId);
            });
            //if (selectedRows.length === 0) {
            //    alert('Please select at least one row to delete.');
            //    return; // Exit the function if no checkboxes are selected
            //}
            if (selectedRows.length > 0) {
                $.ajax({
                    url: '@Url.Action("DeleteMultipleApplications", "Batch")',
                    method: 'POST',
                    data: { rows: selectedRows }
                    //success: function (response) {
                    //    // Handle the server response
                    //    console.log(response);
                    //    alert('Rows deleted successfully');

                    //},
                    //error: function (xhr, status, error) {
                    //    // Handle the AJAX error
                    //    console.log(error);
                    //    alert('An error occurred while deleting rows');
                    //}
                });
            }

        });
    });
</script>

Views/Batch/List.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Core.Flash
@model PagedList<KCC_App.KCCModels.Batch>

@{ ViewData["Title"] = "Batch List"; 
   
}
@Html.Partial("_Flash")

    <div class="container-fluid">
        <div class="animated fadeIn">
        @*<div class="row hide">
                <div class="col-sm-12 text-right">
                    <div class="card">
                        <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit" data-toggle="modal" data-target="#myModal" >
                                <i class="fa fa-upload"></i> Upload
                            </button>
                        <button class="btn btn-sm btn-primary" type="reset" onclick="location.href='@Url.Action("RefreshBatches", "Batch",new { page = Model.PageNumber})'">
                                <i class="fa fa-refresh"></i> Refresh
                            </button>
                        </div>
                    </div>
                </div>
            </div>*@
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-7"><strong><h4>Batch List</h4></strong></div>
                                <div class="col-md-5" style="float: right;">
                                    <div class="row">

                                        <div class="col-md-12" align="right">
                                            <div class="btn-group">
                                                <form action="/Batch/List" method="post">
                                                    <div class="form-actions no-color">
                                                        <div class="btn-group mr-2" role="group" aria-label="First group">
                                                            <input type="text" hidden name="page" value="@Model.PageNumber" />
                                                            <input type="text" class="form-control form-control-sm" name="qry" value="@ViewData["CurrentFilter"]" />
                                                            <input type="submit" value="Search" class="btn btn-sm btn-primary" />
                                                        </div>

                                                    </div>
                                                </form>
                                            </div>
                                            <div class="btn-group" role="group" aria-label="First group">
                                                <button class="btn btn-sm btn-primary" type="submit" data-toggle="modal" data-target="#myModal">
                                                    <i class="fa fa-upload"></i> Upload
                                                </button>
                                            </div>

                                            <div class="btn-group" role="group" aria-label="First group">
                                                <button class="btn btn-sm btn-primary" type="reset" onclick="location.href='@Url.Action("RefreshBatches", "Batch",new { page = Model.PageNumber})'">
                                                    <i class="fa fa-refresh"></i> Refresh
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table table-responsive-sm table-bordered table-striped table-sm">
                                <thead>
                                    <tr>
                                        @*<th style="width:8%;">S No</th>*@
                                        <th>Batch Id</th>
                                        <th>Ackn No.</th>
                                        <th>Financial Year</th>
                                        <th>Submitted On</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var x in Model)
                                    {
                                        @*var index = @Model.IndexOf(x) + 1;*@
                                        <tr>
                                            @*<td>@index</td>*@
                                            <td>@x.batchId</td>
                                            <td>@x.BatchResponseData.batchAckId</td>
                                            <td>@x.financialYear</td>
                                            <td>@x.dateTime</td>
                                           @* <td>@Enum.GetName(typeof(KCC_App.KCCModels.Batch),@x.BatchResponse.datastatus)</td>*@
                                            <td>@x.BatchResponseData.BatchStatus.Name</td>
                                            <td>

                                                <a asp-controller="Batch" asp-action="Detail" asp-route-id="@x.batchId">
                                                    @*<input type="submit" class="btn btn-primary" value="View" />*@
                                                    <button class="btn btn-sm btn-primary" type="submit">
                                                        <i class="fa fa-eye"></i> View
                                                    </button>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <nav>
                            @Html.PagedListPager(Model, page => Url.Action("List", new { page = page }), new PagedListRenderOptions()
                            {
                            ActiveLiElementClass = "active",
                            PageClasses = new[]{ "page-link"},
                            LiElementClasses=new[] { "page-item" },
                            UlElementClasses = new[] { "pagination","mt-3" },
                            LinkToNextPageFormat = "Next",
                            LinkToPreviousPageFormat = "Previous",
                            MaximumPageNumbersToDisplay = 10,
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                            DisplayLinkToNextPage = PagedListDisplayMode.Always
                            })
                            </nav>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <div>
                    <h4 class="modal-title text-center ">Upload</h4>
                </div>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div>
                   <form  name="myform" onSubmit="return validateFileInput()" asp-controller="Batch" asp-action="UploadBatch" method="post" enctype="multipart/form-data">
                       <div class="row">
                           <div class="col-sm-6">
                                <input class="form-control" id="file-to-upload" type="file" name="postedFile" />
                            </div>
                            <div class="col-sm-6 pull-right" >
                                <input  type="submit" class="btn btn-sm btn-dark" value="Upload" />
                            </div>
                        </div>
                   </form>
                </div>
            </div>
            <div class="modal-footer" >
               
                <a href="~/excel/kcc-sample.xls" type="button" class="btn btn-sm btn-primary pull-left"><i class="fa fa-download"></i> Sample</a>
                <button id="button-reset" type="button" class="btn btn-secondary">Clear</button>
           </div>
        </div>
    </div>
</div>

<script>
    $('#button-reset').click(function (e) {
        var $el = $('#file-to-upload');
        $el.wrap('<form>').closest('form').get(0).reset();
        $el.unwrap();
    });
    let output = document.forms['myform']['postedFile'];
    function validateFileInput() {
       
        if (output.value != '') {
            
        } else {
            alert("Please choose file");
            return false;
        }
    }
   
</script>