Controllers/AppController.cs
using Core.Flash;
using DocumentFormat.OpenXml.InkML;
using KCC_App.Data;
using KCC_App.Helpers;
using KCC_App.KCCModels;
using KCC_App.Models;
using KCC_App.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KCC_App.Controllers
{
    [Authentication]
    public class AppController : ControllerBase
    {
        private readonly ILogger<SettingController> _logger;
        //private KCCConfig cCConfig;
        private readonly IFlasher f;
        readonly ApplicationDbContext dbContext;
        private readonly IConfiguration _configuration;
        public AppController(ILogger<SettingController> logger, IConfiguration configuration, ApplicationDbContext context, IFlasher f)
        {
            _logger = logger;
            this._configuration = configuration;
            this.dbContext = context;
            this.f = f;
            //this.cCConfig = context.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
        }
        public IActionResult Setting()
        {

            var years = new List<SelectListItem>();
            int startYear = DateTime.Now.Year-3;
            int endYear = DateTime.Now.Year +5;
            for (var i = startYear; i <= endYear; i++)
            {
                string text = string.Concat(i.ToString(), "-", (i + 1).ToString());
                years.Add(new SelectListItem
                {
                    Text = text,
                    Value = text,
                    Selected = true
                });

            }
            ViewBag.years = new SelectList(years, "Text", "Value"); 
            KCCConfig cCConfig = this.dbContext.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
            //dbContext.Entry(this.cCConfig).State = EntityState.Detached;
            return View(cCConfig);
        }
        [HttpPost]
        public IActionResult Setting(KCCConfig data)
        {
            //dbContext.Remove()
            dbContext.Update(data);
            dbContext.SaveChanges();
            HttpContext.Session.SetString("stateCode", data.StateCode);
            HttpContext.Session.SetString("bankCode", data.BankCode);
            HttpContext.Session.SetString("financialYear", data.FinancialYear);
            f.Flash(Types.Success, "Config updated");
            //Flash("Config update", FlashLevel.Success);
            //Flash.Instance.Success("Config", "Config saved");
            //FlashMessage.Warning("Your error message");
            //this.cCConfig = dbContext.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
            return RedirectToAction("Setting");
        }
        
    }
}

Controllers/SettingController.cs
using Core.Flash;
using Hangfire;
using KCC_App.Data;
using KCC_App.Helpers;
using KCC_App.KCCModels;
using KCC_App.Models;
using KCC_App.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KCC_App.Controllers
{
    [Authentication]
    public class SettingController : ControllerBase
    {
        private readonly ILogger<SettingController> _logger;
        private KCCConfig cCConfig;
        private readonly IFlasher f;
        readonly ApplicationDbContext dbContext;
        private readonly IConfiguration _configuration;
        public SettingController(ILogger<SettingController> logger, IConfiguration configuration, ApplicationDbContext context, IFlasher f)
        {
            _logger = logger;
            this._configuration = configuration;
            this.dbContext = context;
            this.f = f;
            this.cCConfig = context.KCCConfig.AsNoTracking().Include(x=>x.EncryptKey).Include(x=>x.Mapping).FirstOrDefault();
        }
        [HttpGet]
        public IActionResult Manage()
        {
           
            dbContext.Entry(this.cCConfig).State = EntityState.Detached;
            return View(this.cCConfig);
        }

       
        [HttpPost]
        public IActionResult SaveConfig(KCCConfig data)
        {
            
            //dbContext.Remove()
            dbContext.Update(data);
            dbContext.SaveChanges();
            f.Flash(Types.Success, "Config updated");
            //Flash("Config update", FlashLevel.Success);
            //Flash.Instance.Success("Config", "Config saved");
            //FlashMessage.Warning("Your error message");
            //this.cCConfig = dbContext.KCCConfig.AsNoTracking().Include(x => x.EncryptKey).Include(x => x.Mapping).FirstOrDefault();
            return RedirectToAction("Manage");
        }
    }
}

Views/App/Setting.cshtml
@model KCC_App.KCCModels.KCCConfig
@{
    ViewData["Title"] = "Setting";
}
@Html.Partial("_Flash")
@using (Html.BeginForm("Setting", "App", FormMethod.Post))
{
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 text-right">
                    <div class="card">
                        @*<div class="card-header">
                            <strong>Manage Setting</strong>
                        </div>*@
                        @*<div class="card-body">
                            <div class="form-group">
                                <label class="form-col-form-label" for="inputSuccess1">Input with success</label>
                                <input class="form-control is-valid" id="inputSuccess1" type="text">
                            </div>
                            <div class="form-group">
                                <label class="form-col-form-label" for="inputError1">Input with error</label>
                                <input class="form-control is-invalid" id="inputError1" type="text">
                                <div class="invalid-feedback">Please provide a valid informations.</div>
                            </div>
                        </div>*@
                        <div class="card-footer">
                            <button class="btn btn-sm btn-primary" type="submit">
                                <i class="fa fa-dot-circle-o"></i> Submit
                            </button>
                            <button class="btn btn-sm btn-danger" type="reset">
                                <i class="fa fa-ban"></i> Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
                <div class="row">
                <!-- /.col-->
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            <strong>Api Setting</strong>
                            @*<small>Form</small>*@
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="company">Endpoint</label>
                                @Html.TextBoxFor(m => m.EndPoint, new { @class = "form-control", placeholder = "Endpoint Url" })
                            </div>
                            <div class="form-group">
                                <label for="company">AuthKey</label>
                                @Html.TextBoxFor(m => m.AuthKey, new { @class = "form-control", placeholder = "AuthKey" })
                            </div>
                            <div class="form-group hide">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="name">Encryption Id</label>
                                        @Html.TextBoxFor(m => m.EncryptKey.EncryptKeyId, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="vat">IVkey</label>
                                @Html.TextBoxFor(m => m.EncryptKey.IVkey, new { @class = "form-control", placeholder = "IV Key" })
                            </div>
                            <div class="form-group">
                                <label for="vat">Secret Key</label>
                                @Html.TextBoxFor(m => m.EncryptKey.Secretkey, new { @class = "form-control", placeholder = "Secret key" })
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-->
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <strong>Bank Setting</strong>
                                @*<small>Form</small>*@
                            </div>
                            <div class="card-body">
                                <div class="row hide">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="name">Id</label>
                                            @Html.TextBoxFor(m => m.Id, new { @class = "form-control", placeholder = "Id" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="name">Financial Year</label>
                                                @Html.DropDownListFor(m => m.FinancialYear, ViewBag.years as SelectList, new { @class = "form-control" })

                                            @*<input class="form-control" id="name" type="text" placeholder="Enter your name">*@
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="name">Bank Code</label>
                                            @Html.TextBoxFor(m => m.BankCode, new { @class = "form-control", placeholder = "Bank Code" })
                                            @*<input class="form-control" id="name" type="text" placeholder="Enter your name">*@
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="name">State Code</label>
                                            @Html.TextBoxFor(m => m.StateCode, new { @class = "form-control", placeholder = "State Code" })
                                            @*<input class="form-control" id="name" type="text" placeholder="Enter your name">*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- /.row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong>Mapping</strong>
                            </div>
                            <div class="card-body">
                                <table class="table table-responsive-sm table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Key</th>
                                            <th>Mapping</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var property in Model.Mapping.GetType().GetProperties())
                                        {
                                            var value = property.GetValue(Model.Mapping);
                                            var displaycss = property.Name == "MappingId" ? "none" : "block";


                                            @if(property.Name != "MappingId")
                                            {
                                                <tr>
                                                    <td>@property.Name</td>
                                                    <td>
                                                        <input class="form-control" type="text" name="Mapping.@property.Name" value="@value" />
                                                    </td>
                                                </tr>
                                            }

                                          }

                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                        
                    </div>
                    
                </div>
                
            </div>
        </div>
}